import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="h-screen overflow-hidden w-full bg-[#181B23] flex flex-col items-center justify-between py-6 px-4">
          <div className="w-full h-full rounded-[14px] overflow-hidden relative flex flex-col">
            <div className="h-full w-full absolute opacity-50 bg-glow rounded-t" style={{ backgroundImage: "url('/bg.png')", backgroundSize: "cover", backgroundPosition: "center" }}></div>
            {/* Navbar */}
            <div className="w-full rounded-t-[14px] border-x border-t border-[#23263a] bg-[#23263a]/60 shadow-lg flex flex-col overflow-hidden z-10">
              <div className="border-b border-[#23263a] px-4 sm:px-8 pt-4 pb-2">
                <Navbar />
              </div>
            </div>
            {/* Conteúdo principal */}
            <main className="w-full h-full flex-1 flex flex-row overflow-y-auto z-10">
              {children}
            </main>
            {/* Footer */}
            <div className="w-full rounded-b-[14px] border-x border-b border-[#23263a] bg-[#23263a]/60 shadow-lg flex flex-col relative overflow-hidden">
              <div className="border-t border-[#23263a] px-4 sm:px-8 py-3">
                <Footer />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
