import React from "react";
import {
  SiReact,
  SiNextdotjs,
  SiLaravel,
  SiHtml5,
  SiCss,
  SiVuedotjs,
  SiFlutter,
  SiTypescript,
  SiTailwindcss,
  SiStripe,
  SiMongodb,
  SiFirebase,
  SiFramer,
  SiJavascript,
  SiChartdotjs,
  SiMysql,
  SiDart,
  SiGetx,
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiRedis,
  SiDocker,
  SiGit,
  SiFigma,
  SiVercel,
  SiNetlify,
  SiGooglecloud,
} from "@icons-pack/react-simple-icons";

// Mapeamento de ícones
export const technologyIcons: { [key: string]: React.ReactNode } = {
  SiReact: <SiReact className="w-3 h-3" />,
  SiNextdotjs: <SiNextdotjs className="w-3 h-3" />,
  SiLaravel: <SiLaravel className="w-3 h-3" />,
  SiHtml5: <SiHtml5 className="w-3 h-3" />,
  SiCss: <SiCss className="w-3 h-3" />,
  SiVuedotjs: <SiVuedotjs className="w-3 h-3" />,
  SiFlutter: <SiFlutter className="w-3 h-3" />,
  SiTypescript: <SiTypescript className="w-3 h-3" />,
  SiTailwindcss: <SiTailwindcss className="w-3 h-3" />,
  SiStripe: <SiStripe className="w-3 h-3" />,
  SiMongodb: <SiMongodb className="w-3 h-3" />,
  SiFirebase: <SiFirebase className="w-3 h-3" />,
  SiFramer: <SiFramer className="w-3 h-3" />,
  SiJavascript: <SiJavascript className="w-3 h-3" />,
  SiChartdotjs: <SiChartdotjs className="w-3 h-3" />,
  SiMysql: <SiMysql className="w-3 h-3" />,
  SiDart: <SiDart className="w-3 h-3" />,
  SiGetx: <SiGetx className="w-3 h-3" />,
  SiNodedotjs: <SiNodedotjs className="w-3 h-3" />,
  SiExpress: <SiExpress className="w-3 h-3" />,
  SiPostgresql: <SiPostgresql className="w-3 h-3" />,
  SiRedis: <SiRedis className="w-3 h-3" />,
  SiDocker: <SiDocker className="w-3 h-3" />,
  SiGit: <SiGit className="w-3 h-3" />,
  SiFigma: <SiFigma className="w-3 h-3" />,
  SiVercel: <SiVercel className="w-3 h-3" />,
  SiNetlify: <SiNetlify className="w-3 h-3" />,
  SiGooglecloud: <SiGooglecloud className="w-3 h-3" />,
  GSAP: <div className="w-3 h-3 bg-[#88ce02] rounded-sm flex items-center justify-center text-[#000] text-xs font-bold">G</div>,
  AWS: <div className="w-3 h-3 bg-[#ff9900] rounded-sm flex items-center justify-center text-[#000] text-xs font-bold">A</div>,
};
